GET http://localhost:3008

###Login
POST http://localhost:3008/api/login
Content-Type: application/json

{
    "email": "integration_test@gmail.com",
    "password": "integration"
}

###Register Route
POST http://localhost:3008/api/register
Content-Type: application/json

{
    "name": "Daniel Boateng",
    "email": "daniel98@gmail.com",
    "password": "1234567"
}

###Profile
GET http://localhost:3008/api/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjA3NDc1ODYsImV4cCI6MTY1MjMwNTE4NiwiYXVkIjoiNjA5N2MzZmMzMzZiNGEyZjc4NWNlN2M2IiwiaXNzIjoiZGFuaXRvLmNvbSJ9.sG5Hhyq2jJtIOOKDr9qLXVYo2nNXfN31hu4z61BKN68

###Refresh token Route
POST http://localhost:3008/api/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjA3NDUwNDcsImV4cCI6MTY1MjMwMjY0NywiYXVkIjoiNjA5N2I1NmY0Yzk2NzkzMzQ0Y2Q4OWZkIiwiaXNzIjoiZGFuaXRvLmNvbSJ9.FjgFUqVaHgQe5UL2KijOq-yDQbst9GehkYsMr60ue8s"
}

###Logout
DELETE http://localhost:3008/api/logout
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjA3OTMwNTgsImV4cCI6MTY1MjM1MDY1OCwiYXVkIjoiNjA5N2MzZmMzMzZiNGEyZjc4NWNlN2M2IiwiaXNzIjoiZGFuaXRvLmNvbSJ9.NzLDm-PawQyRSw7Nuo2S2mxhncT5hHVqqXvprENWEao