GET http://localhost:30001

###Login
POST http://localhost:3001/auth/login
Content-Type: application/json

{
    "email": "integration_test_1620487611@alttab.co",
    "password": "integration"
}

###Register Route
POST http://localhost:3001/auth/register
Content-Type: application/json

{
    "name": "Daniel Boateng",
    "email": "daniel96@gmail.com",
    "password": "1234567"
}

###Refresh token Route
POST http://localhost:3001/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjA0Nzc2NjIsImV4cCI6MTY1MjAzNTI2MiwiYXVkIjoiNjA5NWMxMTEzYmE1MmIxZGYwOTQ3NTdjIiwiaXNzIjoiZGFuaXRvLmNvbSJ9.n56BMsE3FvuufrUbWzFRAd_rMtL6fTsmnXnR3P83g0A"
}

###Logout
DELETE http://localhost:3001/auth/logout
Content-Type: application/json

{
   "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MjA0Nzc2MzcsImV4cCI6MTY1MjAzNTIzNywiYXVkIjoiNjA5NWMxMTEzYmE1MmIxZGYwOTQ3NTdjIiwiaXNzIjoiZGFuaXRvLmNvbSJ9.FVjNAt7NyDv4MrJZxus6eZXhC2P_YG1qdyau3kpQ53M"
}
